---
pulseapp:
  module: pulseapp.app
  class: PulseApp
  # allows using **kwargs in the app code
  # see: https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#kwargs
  use_dictionary_unpacking: true
